# Generated by Django 2.2.6 on 2020-08-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20200730_1724'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique posts_follow',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_user_author'),
        ),
        migrations.AlterModelTable(
            name='follow',
            table=None,
        ),
    ]
